### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by ananasn** [sasa2002sasha/Lab1#1]
* Ознакомьтесь со стандартом [PEP8](https://www.python.org/dev/peps/pep-0008/), в котором даются указания по оформлению кода на языке Python.
* Очень неудачное именование переменных. `cnt_Symb_W_P_M` - конечно, можно догадаться, что вы имели ввиду without punctuation marks, но это неочевидно. Название переменных должно быть емким и со смыслом (например, можно было назвать `symbols_no_ punctuation`. 
* `i_am_in_skobochki` -- не надо перемешивать транслит и английский язык. Наименование переменных должно быть только на английском.
* Именование переменных должно быть в snake_case (PEP8)
* Не нужно подключать модуль io для того, чтобы открыть файл. Есть встроенные метод open, который делает то же самое. В [документации](https://docs.python.org/3/library/io.html#high-level-module-interface) написано что `This is an alias for the builtin open() function.`
* `low_s[i - 1]` -- не по PEP8 ( пробелы не нужны)
* `cnt_Words +=1` -- не по PEP8 (нужен пробел)
* В вашем случае нужно больше комментариев. Особенно для всех сложных условий. Без них тяжело разобраться.
* Если я правильно поняла, вы тут хотите посчитать количество предложений, при этом исключив аббревиатуры`if cch in '?!' or (cch == '.' and low_s[i-2] != '.'):` . Но например для предложения `The abbreviation i.e. is short for the Latin phrase id est.` ваш код выдаст результатом `Общее количество предложений: 2
`. Потому что первую точку в аббревиатуре он посчитает как конец предложения.
* Почему `i_am_in_skobochki` целое, а не булевое? Вот таких тегов ведь не бывает `<teg1 <teg2>>`

**Comment by ananasn** [comment]
* cch = ch -- бесполезная строчка. Сразу пишите в цикле for нужное название.

**Comment by Jyxerr** [comment]
Я вроде бы исправил
